import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { printSuccess, printError, printInfo } from './display.js';

// ─── Formatters ───────────────────────────────────────────────────────────────

const RISK_EMOJI = {
  High:       '🔴',
  Medium:     '🟡',
  Low:        '🟢',
  Negligible: '⚪',
  'No Risk':  '✅',
};

function riskEmoji(level) {
  return RISK_EMOJI[level] ?? '⚪';
}

function hr(char = '─', len = 60) {
  return char.repeat(len);
}

function mdWrap(text) {
  return (text ?? '').trim();
}

// ─── Markdown builder ─────────────────────────────────────────────────────────

function buildMarkdown(analysis) {
  const { fileName, analysisResult, analysisDate } = analysis;
  const lines = [];
  const date = analysisDate
    ? new Date(analysisDate).toLocaleString(undefined, {
        dateStyle: 'long',
        timeStyle: 'short',
      })
    : new Date().toLocaleString(undefined, { dateStyle: 'long', timeStyle: 'short' });

  // ── Title block ──────────────────────────────────────────────────────────
  lines.push('# UnBind AI — Legal Analysis Report');
  lines.push('');
  lines.push(`**Document:** ${fileName ?? 'Unknown'}`);
  lines.push(`**Generated:** ${date}`);
  lines.push('');
  lines.push(hr('─', 60));
  lines.push('');

  // ── Contract Summary ─────────────────────────────────────────────────────
  lines.push('## 📋 Contract Summary');
  lines.push('');
  lines.push(mdWrap(analysisResult?.summary ?? 'No summary available.'));
  lines.push('');

  // ── Missing Clauses ───────────────────────────────────────────────────────
  const missing = analysisResult?.missingClauses ?? [];
  if (missing.length > 0) {
    lines.push(hr('─', 60));
    lines.push('');
    lines.push('## ⚠️  Potentially Missing Clauses');
    lines.push('');
    missing.forEach((clause, i) => {
      lines.push(`### ${i + 1}. ${clause.clauseName}`);
      lines.push('');
      lines.push(mdWrap(clause.reason));
      lines.push('');
    });
  }

  // ── Clause-by-Clause Analysis ─────────────────────────────────────────────
  const clauses = analysisResult?.clauses ?? [];
  if (clauses.length > 0) {
    lines.push(hr('─', 60));
    lines.push('');
    lines.push('## 🔍 Clause-by-Clause Analysis');
    lines.push('');

    clauses.forEach((clause, i) => {
      const emoji = riskEmoji(clause.riskLevel);
      const risk  = clause.riskLevel ?? 'Unknown';

      lines.push(`### Clause ${i + 1}  ${emoji} ${risk}`);
      lines.push('');

      if (clause.clauseText) {
        lines.push('**Original Text:**');
        lines.push('');
        lines.push('> ' + clause.clauseText.replace(/\n/g, '\n> '));
        lines.push('');
      }

      if (clause.simplifiedExplanation) {
        lines.push('**Plain English:**');
        lines.push('');
        lines.push(mdWrap(clause.simplifiedExplanation));
        lines.push('');
      }

      if (clause.riskReason) {
        lines.push('**Risk:**');
        lines.push('');
        lines.push(mdWrap(clause.riskReason));
        lines.push('');
      }

      if (
        clause.negotiationSuggestion &&
        clause.negotiationSuggestion !== 'No changes needed'
      ) {
        lines.push('**Negotiation Suggestion:**');
        lines.push('');
        lines.push(mdWrap(clause.negotiationSuggestion));
        lines.push('');
      }

      lines.push(hr('─', 40));
      lines.push('');
    });

    // ── Tally ──────────────────────────────────────────────────────────────
    const counts = { High: 0, Medium: 0, Low: 0, Negligible: 0, 'No Risk': 0 };
    clauses.forEach((c) => {
      const k = c.riskLevel in counts ? c.riskLevel : 'Negligible';
      counts[k]++;
    });

    lines.push('## 📊 Risk Summary');
    lines.push('');
    lines.push('| Risk Level | Count |');
    lines.push('|---|---|');
    Object.entries(counts)
      .filter(([, n]) => n > 0)
      .forEach(([lvl, n]) => {
        lines.push(`| ${riskEmoji(lvl)} ${lvl} | ${n} |`);
      });
    lines.push('');
  }

  lines.push(hr('─', 60));
  lines.push('');
  lines.push('*Generated by [UnBind AI](https://unbind.ai) CLI*');
  lines.push('');

  return lines.join('\n');
}

// ─── Plain-text builder ───────────────────────────────────────────────────────

function buildPlainText(analysis) {
  const { fileName, analysisResult, analysisDate } = analysis;
  const lines = [];
  const date = analysisDate
    ? new Date(analysisDate).toLocaleString(undefined, {
        dateStyle: 'long',
        timeStyle: 'short',
      })
    : new Date().toLocaleString(undefined, { dateStyle: 'long', timeStyle: 'short' });

  const rule = '='.repeat(60);
  const subRule = '-'.repeat(60);

  lines.push(rule);
  lines.push('  UNBIND AI — LEGAL ANALYSIS REPORT');
  lines.push(rule);
  lines.push('');
  lines.push(`  Document : ${fileName ?? 'Unknown'}`);
  lines.push(`  Generated: ${date}`);
  lines.push('');
  lines.push(rule);
  lines.push('');

  // Summary
  lines.push('  CONTRACT SUMMARY');
  lines.push(subRule);
  lines.push('');
  lines.push('  ' + (analysisResult?.summary ?? 'No summary available.').replace(/\n/g, '\n  '));
  lines.push('');
  lines.push(rule);
  lines.push('');

  // Missing clauses
  const missing = analysisResult?.missingClauses ?? [];
  if (missing.length > 0) {
    lines.push('  POTENTIALLY MISSING CLAUSES');
    lines.push(subRule);
    lines.push('');
    missing.forEach((clause, i) => {
      lines.push(`  ${i + 1}. ${clause.clauseName}`);
      lines.push('     ' + (clause.reason ?? '').replace(/\n/g, '\n     '));
      lines.push('');
    });
    lines.push(rule);
    lines.push('');
  }

  // Clauses
  const clauses = analysisResult?.clauses ?? [];
  if (clauses.length > 0) {
    lines.push('  CLAUSE-BY-CLAUSE ANALYSIS');
    lines.push(subRule);
    lines.push('');

    clauses.forEach((clause, i) => {
      const risk = clause.riskLevel ?? 'Unknown';
      lines.push(`  Clause ${String(i + 1).padStart(2, '0')}  [${risk}]`);
      lines.push('');

      if (clause.clauseText) {
        lines.push('  Original Text:');
        lines.push('    ' + clause.clauseText.replace(/\n/g, '\n    '));
        lines.push('');
      }
      if (clause.simplifiedExplanation) {
        lines.push('  Plain English:');
        lines.push('    ' + clause.simplifiedExplanation.replace(/\n/g, '\n    '));
        lines.push('');
      }
      if (clause.riskReason) {
        lines.push('  Risk:');
        lines.push('    ' + clause.riskReason.replace(/\n/g, '\n    '));
        lines.push('');
      }
      if (
        clause.negotiationSuggestion &&
        clause.negotiationSuggestion !== 'No changes needed'
      ) {
        lines.push('  Negotiation Suggestion:');
        lines.push('    ' + clause.negotiationSuggestion.replace(/\n/g, '\n    '));
        lines.push('');
      }

      lines.push(subRule);
      lines.push('');
    });

    // Tally
    const counts = { High: 0, Medium: 0, Low: 0, Negligible: 0, 'No Risk': 0 };
    clauses.forEach((c) => {
      const k = c.riskLevel in counts ? c.riskLevel : 'Negligible';
      counts[k]++;
    });
    lines.push('  RISK SUMMARY');
    lines.push('');
    Object.entries(counts)
      .filter(([, n]) => n > 0)
      .forEach(([lvl, n]) => {
        lines.push(`  ${lvl.padEnd(12)} ${n}`);
      });
    lines.push('');
    lines.push(rule);
  }

  lines.push('');
  lines.push('  Generated by UnBind AI CLI');
  lines.push('');

  return lines.join('\n');
}

// ─── Public export function ───────────────────────────────────────────────────

/**
 * Write the analysis report to disk.
 *
 * @param {object} analysis   Full StoredAnalysis object.
 * @param {object} opts
 * @param {string} [opts.outputPath]  Full output path (including filename).
 * @param {'md'|'txt'} [opts.format] 'md' (default) or 'txt'.
 * @param {boolean} [opts.silent]    If true, suppress console output.
 * @returns {string}  The resolved output path.
 */
export function exportAnalysis(analysis, opts = {}) {
  const format = opts.format === 'txt' ? 'txt' : 'md';

  // Derive default output filename from the source document name
  const baseName = path.basename(
    analysis.fileName ?? 'unbind-report',
    path.extname(analysis.fileName ?? '')
  );
  const defaultName = `${baseName}-unbind-report.${format}`;
  const outputPath = opts.outputPath
    ? path.resolve(opts.outputPath)
    : path.resolve(process.cwd(), defaultName);

  const content =
    format === 'txt' ? buildPlainText(analysis) : buildMarkdown(analysis);

  try {
    fs.writeFileSync(outputPath, content, 'utf8');
  } catch (err) {
    throw new Error(`Could not write report: ${err.message}`);
  }

  if (!opts.silent) {
    printSuccess(`Report saved → ${chalk.cyan(outputPath)}`);
    const clauses = analysis.analysisResult?.clauses ?? [];
    const high = clauses.filter((c) => c.riskLevel === 'High').length;
    const missing = analysis.analysisResult?.missingClauses?.length ?? 0;
    printInfo(`${clauses.length} clauses · ${high > 0 ? chalk.red(`${high} high-risk`) : chalk.green('0 high-risk')} · ${missing} missing clause${missing !== 1 ? 's' : ''}`);
  }

  return outputPath;
}
